#############################################################################
# Makefile for building: MainWindow
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Aug 14 19:53:04 2014
# Project:  MainWindow.pro
# Template: app
# Command: /usr/bin/qmake4 -spec /usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ -o Makefile MainWindow.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ -I. -I/usr/local/Trolltech/Qt-4.7.4/include/QtCore -I/usr/local/Trolltech/Qt-4.7.4/include/QtGui -I/usr/local/Trolltech/Qt-4.7.4/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-4.7.4/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.7.4/lib -lQtGui -L/usr/local/Trolltech/Qt-4.7.4/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp \
		qrc_menu.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o \
		qrc_menu.o
DIST          = /usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf \
		MainWindow.pro
QMAKE_TARGET  = MainWindow
DESTDIR       = 
TARGET        = MainWindow

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MainWindow.pro  /usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.7.4/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ -o Makefile MainWindow.pro
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.7.4/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.7.4/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.7.4/mkspecs/linux-g++ -o Makefile MainWindow.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MainWindow1.0.0 || $(MKDIR) .tmp/MainWindow1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MainWindow1.0.0/ && $(COPY_FILE) --parents mainwindow.h .tmp/MainWindow1.0.0/ && $(COPY_FILE) --parents menu.qrc menu.qrc .tmp/MainWindow1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp .tmp/MainWindow1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/MainWindow1.0.0/ && (cd `dirname .tmp/MainWindow1.0.0` && $(TAR) MainWindow1.0.0.tar MainWindow1.0.0 && $(COMPRESS) MainWindow1.0.0.tar) && $(MOVE) `dirname .tmp/MainWindow1.0.0`/MainWindow1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MainWindow1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/local/Trolltech/Qt-4.7.4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all: qrc_menu.cpp qrc_menu.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_menu.cpp qrc_menu.cpp
qrc_menu.cpp: menu.qrc \
		images/gtk-help.png \
		images/gnome-stock-mail-new.png \
		images/gtk-goto-top.png \
		images/gtk-save-as.png \
		images/mail_forward.png \
		images/revert.png \
		images/stock_bottom.png \
		images/stock_help.png \
		images/tab_new.png \
		images/document-open-recent.png \
		images/stock_properties.png \
		images/window-new.png \
		images/remove.png \
		images/stock_mail-compose.png \
		images/stock_help-add-bookmark.png \
		images/object-flip-vertical.png \
		images/filesaveas.png \
		images/stock_text_justify.png \
		images/go-home.png \
		images/gtk-media-forward-ltr.png \
		images/gtk-find.png \
		images/edit-undo.png \
		images/player_end.png \
		images/stock_text_unindent.png \
		images/redhat-home.png \
		images/edit-cut.png \
		images/media-seek-backward.png \
		images/text_strike.png \
		images/gnome-searchtool.png \
		images/mail-mark-junk.png \
		images/stock_home.png \
		images/player_eject.png \
		images/stock_text-strikethrough.png \
		images/stock_mail-reply.png \
		images/list-add.png \
		images/gtk-sort-descending.png \
		images/fileopen.png \
		images/stock_text_indent.png \
		images/gnome-lockscreen.png \
		images/gtk-about.png \
		images/help.png \
		images/view-restore.png \
		images/gnome-run.png \
		images/stock_new-appointment.png \
		images/application-exit.png \
		images/viewmag1.png \
		images/stock_new-dir.png \
		images/stock_mail-send-receive.png \
		images/stock_media-play.png \
		images/gnome-stock-mail-fwd.png \
		images/finish.png \
		images/stock_print-preview.png \
		images/go-first.png \
		images/mail-mark-notjunk.png \
		images/gtk-save.png \
		images/stock_last.png \
		images/edit-paste.png \
		images/gtk-leave-fullscreen.png \
		images/gtk-home.png \
		images/gtk-zoom-fit.png \
		images/document-save.png \
		images/gtk-zoom-100.png \
		images/editdelete.png \
		images/gtk-edit.png \
		images/lock.png \
		images/reload_page.png \
		images/gtk-strikethrough.png \
		images/gtk-properties.png \
		images/gtk-indent-rtl.png \
		images/stock_save-as.png \
		images/call-stop.png \
		images/gtk-spell-check.png \
		images/gtk-italic.png \
		images/redo.png \
		images/gnome-stock-text-indent.png \
		images/kfm_home.png \
		images/filenew.png \
		images/player_stop.png \
		images/format-text-direction-ltr.png \
		images/go-jump.png \
		images/go-previous.png \
		images/forward.png \
		images/gtk-revert-to-saved-ltr.png \
		images/mail_new.png \
		images/window_new.png \
		images/reload3.png \
		images/gtk-go-forward-rtl.png \
		images/stock_media-fwd.png \
		images/stock_new-address-book.png \
		images/stock_search-and-replace.png \
		images/player_pause.png \
		images/gtk-media-pause.png \
		images/reload.png \
		images/gnome-stock-mail-rpl.png \
		images/gtk-bold.png \
		images/player_record.png \
		images/stock_media-rec.png \
		images/stock_left.png \
		images/stock_save.png \
		images/edit-copy.png \
		images/gtk-cancel.png \
		images/document-print-preview.png \
		images/format-text-strikethrough.png \
		images/gnome-session-logout.png \
		images/folder-new.png \
		images/start.png \
		images/stock_fullscreen.png \
		images/centrejust.png \
		images/view-sort-ascending.png \
		images/gtk-close.png \
		images/gtk-justify-left.png \
		images/stock_media-pause.png \
		images/editpaste.png \
		images/stock_new-bcard.png \
		images/edit-redo.png \
		images/gtk-fullscreen.png \
		images/view-sort-descending.png \
		images/filefind.png \
		images/stock_text_italic.png \
		images/zoom-best-fit.png \
		images/next.png \
		images/up.png \
		images/viewmag+.png \
		images/gtk-add.png \
		images/exit.png \
		images/gtk-remove.png \
		images/mail_replyall.png \
		images/edit-find.png \
		images/stock_spam.png \
		images/media-playback-stop.png \
		images/zoom-original.png \
		images/gtk-print-preview.png \
		images/add.png \
		images/gtk-media-forward-rtl.png \
		images/stock_stop.png \
		images/system-run.png \
		images/format-justify-fill.png \
		images/mail-mark-unread.png \
		images/window_nofullscreen.png \
		images/stock_media-stop.png \
		images/edit-clear.png \
		images/fileprint.png \
		images/stock_mail-send.png \
		images/stock_mail-forward.png \
		images/stock_first.png \
		images/gtk-unindent-ltr.png \
		images/document-open.png \
		images/stock_paste.png \
		images/format-text-underline.png \
		images/stock_undo.png \
		images/system-search.png \
		images/stock_leave-fullscreen.png \
		images/help-contents.png \
		images/gtk-cut.png \
		images/down.png \
		images/call-start.png \
		images/system-log-out.png \
		images/gtk-paste.png \
		images/gtk-print.png \
		images/list-remove.png \
		images/document-new.png \
		images/system-lock-screen.png \
		images/text_bold.png \
		images/format-justify-center.png \
		images/edit-find-replace.png \
		images/zoom-in.png \
		images/contact-new.png \
		images/gtk-execute.png \
		images/gtk-media-record.png \
		images/bottom.png \
		images/stock_print-setup.png \
		images/gtk-select-all.png \
		images/media-skip-forward.png \
		images/gtk-goto-first-ltr.png \
		images/filequickprint.png \
		images/stock_copy.png \
		images/gtk-go-back-rtl.png \
		images/format-justify-right.png \
		images/stock_text_underlined.png \
		images/editclear.png \
		images/stock_mail-reply-to-all.png \
		images/stock_zoom-out.png \
		images/gtk-goto-bottom.png \
		images/mail_spam.png \
		images/stock_media-rew.png \
		images/gtk-open.png \
		images/address-book-new.png \
		images/view-fullscreen.png \
		images/bookmark_add.png \
		images/player_play.png \
		images/stock_new-text.png \
		images/mail-reply-sender.png \
		images/media-playback-start.png \
		images/text_italic.png \
		images/gtk-indent-ltr.png \
		images/media-record.png \
		images/object-rotate-right.png \
		images/top.png \
		images/format-text-direction-rtl.png \
		images/mail-send.png \
		images/window-close.png \
		images/stock_file-properites.png \
		images/bookmarks_list_add.png \
		images/Thumbs.db \
		images/stock_top.png \
		images/mail-send-receive.png \
		images/media-eject.png \
		images/stock_text_center.png \
		images/stock_about.png \
		images/go-bottom.png \
		images/gnome-stock-text-unindent.png \
		images/xfce-system-exit.png \
		images/back.png \
		images/bookmark-new.png \
		images/stock_text_right.png \
		images/gtk-media-previous-ltr.png \
		images/tools-check-spelling.png \
		images/search.png \
		images/format-indent-more.png \
		images/stock_redo.png \
		images/gtk-find-and-replace.png \
		images/editcut.png \
		images/gtk-media-rewind-rtl.png \
		images/window_fullscreen.png \
		images/gtk-jump-to-ltr.png \
		images/gtk-zoom-in.png \
		images/find.png \
		images/mail-mark-read.png \
		images/help-faq.png \
		images/gtk-justify-right.png \
		images/player_start.png \
		images/gtk-justify-center.png \
		images/stock_zoom-in.png \
		images/gtk-sort-ascending.png \
		images/stock_refresh.png \
		images/insert-object.png \
		images/gtk-unindent-rtl.png \
		images/gtk-media-next-rtl.png \
		images/view-refresh.png \
		images/stock_print.png \
		images/stock_media-prev.png \
		images/gtk-goto-last-ltr.png \
		images/gnome-stock-mail-snd.png \
		images/stock_spellcheck.png \
		images/gtk-zoom-out.png \
		images/viewmagfit.png \
		images/document-revert.png \
		images/process-stop.png \
		images/edit-select-all.png \
		images/gtk-goto-first-rtl.png \
		images/gtk-new.png \
		images/stock_search.png \
		images/gtk-undo-ltr.png \
		images/insert-text.png \
		images/format-indent-less.png \
		images/stock_new-tab.png \
		images/go-down.png \
		images/stock_zoom-1.png \
		images/player_fwd.png \
		images/stock_cut.png \
		images/format-text-italic.png \
		images/viewmag-.png \
		images/gohome.png \
		images/mail-message-new.png \
		images/gtk-media-previous-rtl.png \
		images/document-print.png \
		images/stock_add-bookmark.png \
		images/reload_all_tabs.png \
		images/stop.png \
		images/rightjust.png \
		images/format-text-bold.png \
		images/gtk-go-forward-ltr.png \
		images/gnome-shutdown.png \
		images/stock_text_bold.png \
		images/format-justify-left.png \
		images/stock_close.png \
		images/gtk-refresh.png \
		images/system-shutdown.png \
		images/object-rotate-left.png \
		images/stock_up.png \
		images/go-top.png \
		images/media-playback-pause.png \
		images/document-send.png \
		images/undo.png \
		images/gtk-go-down.png \
		images/mail_send.png \
		images/gtk-copy.png \
		images/mail-mark-important.png \
		images/document-page-setup.png \
		images/previous.png \
		images/insert-link.png \
		images/stock_media-next.png \
		images/gnome-logout.png \
		images/document-save-as.png \
		images/filesave.png \
		images/stock_delete.png \
		images/stock_new-window.png \
		images/go-last.png \
		images/stock_zoom-page.png \
		images/text_under.png \
		images/mail_reply.png \
		images/insert-image.png \
		images/help-about.png \
		images/edit-delete.png \
		images/kfind.png \
		images/stock_select-all.png \
		images/gtk-media-stop.png \
		images/gtk-goto-last-rtl.png \
		images/object-flip-horizontal.png \
		images/document-properties.png \
		images/gtk-clear.png \
		images/gtk-redo-ltr.png \
		images/folder_new.png \
		images/xfce-system-lock.png \
		images/zoom-fit-best.png \
		images/appointment.png \
		images/gtk-stop.png \
		images/mail-forward.png \
		images/gtk-jump-to-rtl.png \
		images/gtk-media-next-ltr.png \
		images/gtk-delete.png \
		images/gtk-justify-fill.png \
		images/go-next.png \
		images/gtk-go-up.png \
		images/editcopy.png \
		images/media-skip-backward.png \
		images/mail-reply-all.png \
		images/go-up.png \
		images/stock_down.png \
		images/gtk-revert-to-saved-rtl.png \
		images/gtk-go-back-ltr.png \
		images/tab-new.png \
		images/stock_right.png \
		images/gtk-underline.png \
		images/gtk-media-rewind-ltr.png \
		images/leftjust.png \
		images/gtk-quit.png \
		images/appointment-new.png \
		images/media-seek-forward.png \
		images/stock_text_left.png \
		images/gtk-media-play-ltr.png \
		images/player_rew.png
	/usr/local/Trolltech/Qt-4.7.4/bin/rcc -name menu menu.qrc -o qrc_menu.cpp

qrc_menu.cpp: menu.qrc \
		images/gtk-help.png \
		images/gnome-stock-mail-new.png \
		images/gtk-goto-top.png \
		images/gtk-save-as.png \
		images/mail_forward.png \
		images/revert.png \
		images/stock_bottom.png \
		images/stock_help.png \
		images/tab_new.png \
		images/document-open-recent.png \
		images/stock_properties.png \
		images/window-new.png \
		images/remove.png \
		images/stock_mail-compose.png \
		images/stock_help-add-bookmark.png \
		images/object-flip-vertical.png \
		images/filesaveas.png \
		images/stock_text_justify.png \
		images/go-home.png \
		images/gtk-media-forward-ltr.png \
		images/gtk-find.png \
		images/edit-undo.png \
		images/player_end.png \
		images/stock_text_unindent.png \
		images/redhat-home.png \
		images/edit-cut.png \
		images/media-seek-backward.png \
		images/text_strike.png \
		images/gnome-searchtool.png \
		images/mail-mark-junk.png \
		images/stock_home.png \
		images/player_eject.png \
		images/stock_text-strikethrough.png \
		images/stock_mail-reply.png \
		images/list-add.png \
		images/gtk-sort-descending.png \
		images/fileopen.png \
		images/stock_text_indent.png \
		images/gnome-lockscreen.png \
		images/gtk-about.png \
		images/help.png \
		images/view-restore.png \
		images/gnome-run.png \
		images/stock_new-appointment.png \
		images/application-exit.png \
		images/viewmag1.png \
		images/stock_new-dir.png \
		images/stock_mail-send-receive.png \
		images/stock_media-play.png \
		images/gnome-stock-mail-fwd.png \
		images/finish.png \
		images/stock_print-preview.png \
		images/go-first.png \
		images/mail-mark-notjunk.png \
		images/gtk-save.png \
		images/stock_last.png \
		images/edit-paste.png \
		images/gtk-leave-fullscreen.png \
		images/gtk-home.png \
		images/gtk-zoom-fit.png \
		images/document-save.png \
		images/gtk-zoom-100.png \
		images/editdelete.png \
		images/gtk-edit.png \
		images/lock.png \
		images/reload_page.png \
		images/gtk-strikethrough.png \
		images/gtk-properties.png \
		images/gtk-indent-rtl.png \
		images/stock_save-as.png \
		images/call-stop.png \
		images/gtk-spell-check.png \
		images/gtk-italic.png \
		images/redo.png \
		images/gnome-stock-text-indent.png \
		images/kfm_home.png \
		images/filenew.png \
		images/player_stop.png \
		images/format-text-direction-ltr.png \
		images/go-jump.png \
		images/go-previous.png \
		images/forward.png \
		images/gtk-revert-to-saved-ltr.png \
		images/mail_new.png \
		images/window_new.png \
		images/reload3.png \
		images/gtk-go-forward-rtl.png \
		images/stock_media-fwd.png \
		images/stock_new-address-book.png \
		images/stock_search-and-replace.png \
		images/player_pause.png \
		images/gtk-media-pause.png \
		images/reload.png \
		images/gnome-stock-mail-rpl.png \
		images/gtk-bold.png \
		images/player_record.png \
		images/stock_media-rec.png \
		images/stock_left.png \
		images/stock_save.png \
		images/edit-copy.png \
		images/gtk-cancel.png \
		images/document-print-preview.png \
		images/format-text-strikethrough.png \
		images/gnome-session-logout.png \
		images/folder-new.png \
		images/start.png \
		images/stock_fullscreen.png \
		images/centrejust.png \
		images/view-sort-ascending.png \
		images/gtk-close.png \
		images/gtk-justify-left.png \
		images/stock_media-pause.png \
		images/editpaste.png \
		images/stock_new-bcard.png \
		images/edit-redo.png \
		images/gtk-fullscreen.png \
		images/view-sort-descending.png \
		images/filefind.png \
		images/stock_text_italic.png \
		images/zoom-best-fit.png \
		images/next.png \
		images/up.png \
		images/viewmag+.png \
		images/gtk-add.png \
		images/exit.png \
		images/gtk-remove.png \
		images/mail_replyall.png \
		images/edit-find.png \
		images/stock_spam.png \
		images/media-playback-stop.png \
		images/zoom-original.png \
		images/gtk-print-preview.png \
		images/add.png \
		images/gtk-media-forward-rtl.png \
		images/stock_stop.png \
		images/system-run.png \
		images/format-justify-fill.png \
		images/mail-mark-unread.png \
		images/window_nofullscreen.png \
		images/stock_media-stop.png \
		images/edit-clear.png \
		images/fileprint.png \
		images/stock_mail-send.png \
		images/stock_mail-forward.png \
		images/stock_first.png \
		images/gtk-unindent-ltr.png \
		images/document-open.png \
		images/stock_paste.png \
		images/format-text-underline.png \
		images/stock_undo.png \
		images/system-search.png \
		images/stock_leave-fullscreen.png \
		images/help-contents.png \
		images/gtk-cut.png \
		images/down.png \
		images/call-start.png \
		images/system-log-out.png \
		images/gtk-paste.png \
		images/gtk-print.png \
		images/list-remove.png \
		images/document-new.png \
		images/system-lock-screen.png \
		images/text_bold.png \
		images/format-justify-center.png \
		images/edit-find-replace.png \
		images/zoom-in.png \
		images/contact-new.png \
		images/gtk-execute.png \
		images/gtk-media-record.png \
		images/bottom.png \
		images/stock_print-setup.png \
		images/gtk-select-all.png \
		images/media-skip-forward.png \
		images/gtk-goto-first-ltr.png \
		images/filequickprint.png \
		images/stock_copy.png \
		images/gtk-go-back-rtl.png \
		images/format-justify-right.png \
		images/stock_text_underlined.png \
		images/editclear.png \
		images/stock_mail-reply-to-all.png \
		images/stock_zoom-out.png \
		images/gtk-goto-bottom.png \
		images/mail_spam.png \
		images/stock_media-rew.png \
		images/gtk-open.png \
		images/address-book-new.png \
		images/view-fullscreen.png \
		images/bookmark_add.png \
		images/player_play.png \
		images/stock_new-text.png \
		images/mail-reply-sender.png \
		images/media-playback-start.png \
		images/text_italic.png \
		images/gtk-indent-ltr.png \
		images/media-record.png \
		images/object-rotate-right.png \
		images/top.png \
		images/format-text-direction-rtl.png \
		images/mail-send.png \
		images/window-close.png \
		images/stock_file-properites.png \
		images/bookmarks_list_add.png \
		images/Thumbs.db \
		images/stock_top.png \
		images/mail-send-receive.png \
		images/media-eject.png \
		images/stock_text_center.png \
		images/stock_about.png \
		images/go-bottom.png \
		images/gnome-stock-text-unindent.png \
		images/xfce-system-exit.png \
		images/back.png \
		images/bookmark-new.png \
		images/stock_text_right.png \
		images/gtk-media-previous-ltr.png \
		images/tools-check-spelling.png \
		images/search.png \
		images/format-indent-more.png \
		images/stock_redo.png \
		images/gtk-find-and-replace.png \
		images/editcut.png \
		images/gtk-media-rewind-rtl.png \
		images/window_fullscreen.png \
		images/gtk-jump-to-ltr.png \
		images/gtk-zoom-in.png \
		images/find.png \
		images/mail-mark-read.png \
		images/help-faq.png \
		images/gtk-justify-right.png \
		images/player_start.png \
		images/gtk-justify-center.png \
		images/stock_zoom-in.png \
		images/gtk-sort-ascending.png \
		images/stock_refresh.png \
		images/insert-object.png \
		images/gtk-unindent-rtl.png \
		images/gtk-media-next-rtl.png \
		images/view-refresh.png \
		images/stock_print.png \
		images/stock_media-prev.png \
		images/gtk-goto-last-ltr.png \
		images/gnome-stock-mail-snd.png \
		images/stock_spellcheck.png \
		images/gtk-zoom-out.png \
		images/viewmagfit.png \
		images/document-revert.png \
		images/process-stop.png \
		images/edit-select-all.png \
		images/gtk-goto-first-rtl.png \
		images/gtk-new.png \
		images/stock_search.png \
		images/gtk-undo-ltr.png \
		images/insert-text.png \
		images/format-indent-less.png \
		images/stock_new-tab.png \
		images/go-down.png \
		images/stock_zoom-1.png \
		images/player_fwd.png \
		images/stock_cut.png \
		images/format-text-italic.png \
		images/viewmag-.png \
		images/gohome.png \
		images/mail-message-new.png \
		images/gtk-media-previous-rtl.png \
		images/document-print.png \
		images/stock_add-bookmark.png \
		images/reload_all_tabs.png \
		images/stop.png \
		images/rightjust.png \
		images/format-text-bold.png \
		images/gtk-go-forward-ltr.png \
		images/gnome-shutdown.png \
		images/stock_text_bold.png \
		images/format-justify-left.png \
		images/stock_close.png \
		images/gtk-refresh.png \
		images/system-shutdown.png \
		images/object-rotate-left.png \
		images/stock_up.png \
		images/go-top.png \
		images/media-playback-pause.png \
		images/document-send.png \
		images/undo.png \
		images/gtk-go-down.png \
		images/mail_send.png \
		images/gtk-copy.png \
		images/mail-mark-important.png \
		images/document-page-setup.png \
		images/previous.png \
		images/insert-link.png \
		images/stock_media-next.png \
		images/gnome-logout.png \
		images/document-save-as.png \
		images/filesave.png \
		images/stock_delete.png \
		images/stock_new-window.png \
		images/go-last.png \
		images/stock_zoom-page.png \
		images/text_under.png \
		images/mail_reply.png \
		images/insert-image.png \
		images/help-about.png \
		images/edit-delete.png \
		images/kfind.png \
		images/stock_select-all.png \
		images/gtk-media-stop.png \
		images/gtk-goto-last-rtl.png \
		images/object-flip-horizontal.png \
		images/document-properties.png \
		images/gtk-clear.png \
		images/gtk-redo-ltr.png \
		images/folder_new.png \
		images/xfce-system-lock.png \
		images/zoom-fit-best.png \
		images/appointment.png \
		images/gtk-stop.png \
		images/mail-forward.png \
		images/gtk-jump-to-rtl.png \
		images/gtk-media-next-ltr.png \
		images/gtk-delete.png \
		images/gtk-justify-fill.png \
		images/go-next.png \
		images/gtk-go-up.png \
		images/editcopy.png \
		images/media-skip-backward.png \
		images/mail-reply-all.png \
		images/go-up.png \
		images/stock_down.png \
		images/gtk-revert-to-saved-rtl.png \
		images/gtk-go-back-ltr.png \
		images/tab-new.png \
		images/stock_right.png \
		images/gtk-underline.png \
		images/gtk-media-rewind-ltr.png \
		images/leftjust.png \
		images/gtk-quit.png \
		images/appointment-new.png \
		images/media-seek-forward.png \
		images/stock_text_left.png \
		images/gtk-media-play-ltr.png \
		images/player_rew.png
	/usr/local/Trolltech/Qt-4.7.4/bin/rcc -name menu menu.qrc -o qrc_menu.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/local/Trolltech/Qt-4.7.4/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

qrc_menu.o: qrc_menu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_menu.o qrc_menu.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

